import type { Metadata } from 'next'

import './globals.css'

import { PropsWithChildren } from 'react'

import Providers from '@/shared/components/Providers'
import { Inter, Source_Serif_4 } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const sourceSerif = Source_Serif_4({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--font-source-serif'
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sourceSerif.variable} ${inter.variable}`}
    >
      <body className="bg-background-light dark:bg-background-dark text-base-light dark:text-base-dark pt-11">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
