import type { Metadata } from 'next'

import './globals.css'

import { PropsWithChildren } from 'react'

import MswWrapper from '@/msw/MswWrapper/MswWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <MswWrapper>{children}</MswWrapper>
      </body>
    </html>
  )
}
